/**
 * Blender integration, the model side.
 *
 * Before Effects keeps a link per Blender job in the project: an effect it generated (smoke, fire,
 * liquid, cloth — physical simulations Blender is good at), or a person's own .blend linked in. To
 * build or render one it hands Blender an exchange file (below): the show camera — so Blender's
 * render lines up exactly with the canvas — the building's solids with the photo, the effect's
 * emitter and domain, the frame range, and who simulates each object:
 *
 *   owner "before-effects"  moved by keyframes or by motion Before Effects already prepared with
 *                           its own physics (Rapier); Blender plays it back and treats it as an
 *                           obstacle — it never simulates it.
 *   owner "blender"         simulated by Blender (smoke, fire, liquid, cloth).
 *
 * An object has exactly one owner. Blender renders the effect with the building as a holdout (it
 * hides what's behind it but isn't drawn), with a transparent background, and the result comes back
 * as an ordinary video layer that sits exactly on the canvas.
 *
 * Coordinates in the exchange are Before Effects' (metres; x right, y up, z toward the audience);
 * the Blender scripts convert to Blender's (z up).
 */
import earcut from "earcut";
import polygonClipping from "polygon-clipping";
import { z } from "zod";
import { refRegions, regionHoles } from "./areas.ts";
import type { Id, Project, Vec2, Vec3 } from "./model.ts";
import { defineOp, OpError } from "./ops.ts";
import { flattenPath } from "./pathmath.ts";
import { evalProp } from "./anim.ts";
import { secondsToTime } from "./time.ts";
import { rand01 } from "./rng.ts";
import { type Canvas, canvasToWorld, eulerDegToQuat, fracture, METERS_PER_PIXEL, placePoint, type ResolvedPiece, type ResolvedScene3D, showCamera } from "./world3d.ts";

export type BlenderEffectKind = "smoke" | "fire" | "liquid" | "cloth" | "shatter";

export const BLENDER_EFFECTS: Record<BlenderEffectKind, { title: string; description: string }> = {
  smoke: { title: "Smoke (Blender)", description: "Billowing smoke rising from the area, simulated by Blender around the house." },
  fire: { title: "Fire (Blender)", description: "Flames and smoke from the area, simulated by Blender." },
  liquid: { title: "Water pouring (Blender)", description: "Water gushing out of the area and splashing down the front of the house, simulated by Blender." },
  cloth: { title: "Cloth reveal (Blender)", description: "A sheet hangs over the area, then lets go and falls away to reveal it — real cloth, simulated by Blender, crumpling at the foot of the house." },
  shatter: {
    title: "Break apart (Blender)",
    description:
      "The area breaks into pieces that fall with Blender's rigid-body physics, carrying the photo, and land on the house and the ground; rendered as a video. The built-in Collapse, Explode and Crumble (3D) stay available and adjust live.",
  },
};

export interface BlenderLink {
  readonly id: Id;
  readonly name: string;
  /** Generated by Before Effects for an effect, or a person's own .blend linked in. */
  readonly origin: "effect" | "linked";
  readonly effect?: {
    readonly kind: BlenderEffectKind;
    readonly regionIds: readonly Id[];
    /** Strength 0..1, colour, … (per kind). */
    readonly params: Readonly<Record<string, number | string | boolean>>;
  };
  /** The .blend file (Before Effects writes it for effects; for linked files it's the person's). */
  readonly blendFile?: string;
  /** Scene (composition) it plays in, when it starts there, and how long it lasts. */
  readonly compId: Id;
  readonly startSeconds: number;
  readonly seconds: number;
  /** Render size: half (quicker) or full canvas resolution. */
  readonly quality: "draft" | "full";
  /** The last render: a video with transparency, and the .blend's modification time it was made from. */
  readonly result?: { readonly assetId: Id; readonly renderedAt: string; readonly blendMtime?: number; readonly seconds: number };
  /** The layer showing the result. */
  readonly layerId?: Id;
}

/** A setting of a Blender effect, shown in the inspector; changing it means simulating again. */
export interface BlenderParamSpec {
  readonly key: string;
  readonly label: string;
  readonly kind: "color" | "number";
  readonly default: number | string;
  readonly min?: number;
  readonly max?: number;
  readonly step?: number;
  readonly unit?: string;
  readonly help?: string;
}

/** Every setting each effect has (be_blender.py reads the same keys and defaults). */
export const BLENDER_PARAMS: Record<BlenderEffectKind, readonly BlenderParamSpec[]> = {
  smoke: [
    { key: "color", label: "Colour", kind: "color", default: "#bfbfc7" },
    { key: "density", label: "Thickness", kind: "number", default: 4, min: 0.5, max: 10, step: 0.1, help: "How much smoke the area gives off." },
    { key: "swirl", label: "Swirl", kind: "number", default: 0.5, min: 0, max: 2, step: 0.05, help: "Curling detail as it rises." },
    { key: "linger", label: "Lingers for", kind: "number", default: 2.7, min: 0.3, max: 10, step: 0.1, unit: "s", help: "How long the smoke lasts before thinning out." },
  ],
  fire: [
    { key: "fuel", label: "Fuel", kind: "number", default: 1.2, min: 0.2, max: 3, step: 0.05, help: "More fuel: bigger, taller flames." },
    { key: "density", label: "Smoke from the source", kind: "number", default: 4, min: 0, max: 10, step: 0.1 },
    { key: "swirl", label: "Swirl", kind: "number", default: 0.5, min: 0, max: 2, step: 0.05 },
    { key: "linger", label: "Smoke lingers for", kind: "number", default: 0.8, min: 0.2, max: 10, step: 0.1, unit: "s" },
    { key: "color", label: "Smoke colour", kind: "color", default: "#383333" },
  ],
  liquid: [
    { key: "color", label: "Water colour", kind: "color", default: "#296bd9" },
    { key: "push", label: "Bursts out at", kind: "number", default: 1.5, min: 0, max: 5, step: 0.1, unit: "m/s", help: "How hard the water comes out toward the audience." },
    { key: "pourFor", label: "Pours for", kind: "number", default: 1, min: 0.1, max: 30, step: 0.1, unit: "s", help: "Then it stops, falls and runs off." },
  ],
  shatter: [
    { key: "pieceSize", label: "Piece size", kind: "number", default: 60, min: 15, max: 300, step: 1, unit: "cm", help: "Smaller pieces: more of them (up to 400)." },
    { key: "breakAt", label: "Breaks at", kind: "number", default: 1, min: 0, max: 30, step: 0.1, unit: "s", help: "From the start of the effect." },
    { key: "stagger", label: "Lets go over", kind: "number", default: 0, min: 0, max: 5, step: 0.1, unit: "s", help: "0: all at once. Longer: the top gives way first and the rest follows (crumbling)." },
    { key: "push", label: "Push toward the audience", kind: "number", default: 1.5, min: 0, max: 8, step: 0.1, unit: "m/s" },
    { key: "spin", label: "Tumble", kind: "number", default: 0.5, min: 0, max: 3, step: 0.05, unit: "turns/s" },
    { key: "bounce", label: "Bounce", kind: "number", default: 0.15, min: 0, max: 1, step: 0.05 },
    { key: "friction", label: "Friction", kind: "number", default: 0.7, min: 0, max: 2, step: 0.05 },
    { key: "seed", label: "Variation", kind: "number", default: 1, min: 1, max: 99, step: 1 },
  ],
  cloth: [
    { key: "color", label: "Sheet colour", kind: "color", default: "#ebebe6" },
    { key: "revealAt", label: "Lets go at", kind: "number", default: 1.2, min: 0.3, max: 30, step: 0.1, unit: "s", help: "When the sheet drops, from the start of the effect." },
  ],
};

// ---- operations ---------------------------------------------------------------------------------------

const linkShape = z.custom<BlenderLink>((v) => {
  const l = v as BlenderLink;
  return !!l && typeof l.id === "string" && (l.origin === "effect" || l.origin === "linked") && typeof l.compId === "string";
}, { message: "Not a valid Blender link." });

export const blenderSet = defineOp({
  type: "blender.set",
  title: "Blender link",
  description: "Add or replace a Blender job (an effect simulated in Blender, or a linked .blend) in the project.",
  args: z.object({ link: linkShape }),
  apply: (d, a) => {
    const all = ((d as { blenderLinks?: Record<Id, BlenderLink> }).blenderLinks ??= {});
    all[a.link.id] = a.link as never;
  },
});

export const blenderRemove = defineOp({
  type: "blender.remove",
  title: "Remove Blender link",
  description: "Remove a Blender job from the project (its rendered video stays as media).",
  args: z.object({ linkId: z.string() }),
  apply: (d, a) => {
    const all = (d as { blenderLinks?: Record<Id, BlenderLink> }).blenderLinks;
    if (!all?.[a.linkId]) throw new OpError("That Blender link no longer exists.");
    delete all[a.linkId];
  },
});

export const blenderOps = [blenderSet, blenderRemove];

// ---- the exchange -----------------------------------------------------------------------------------------

export const EXCHANGE_VERSION = 1;

/** A closed solid as triangles (Before Effects coordinates), with photo coordinates per vertex. */
export interface ExchangeMesh {
  readonly verts: ReadonlyArray<readonly [number, number, number]>;
  readonly tris: ReadonlyArray<readonly [number, number, number]>;
  /** Photo texture coordinates (0..1, origin top-left of the canvas). */
  readonly uvs?: ReadonlyArray<readonly [number, number]>;
}

export interface ExchangeObject {
  readonly name: string;
  readonly owner: "before-effects" | "blender";
  /** obstacle: hides what's behind it and blocks the simulation · emitter / cloth: the simulated thing. */
  readonly role: "obstacle" | "emitter" | "cloth" | "ground" | "debris" | "backdrop";
  readonly mesh: ExchangeMesh;
  /** Photo on the front (for cloth that shows the photo; obstacles are holdouts). */
  readonly photo?: boolean;
  /** Played-back motion (owner before-effects): per frame from frame 1, [x,y,z, qx,qy,qz,qw]. */
  readonly motion?: ReadonlyArray<readonly number[]>;
  /**
   * Cloth only: vertices held by a handle, the handle's keyframes [frame, dx, dy, dz] (metres, from
   * where it starts), and the frame each held vertex lets go (parallel to `verts`; absent = held
   * throughout). The rest of the sheet is simulated and follows.
   */
  readonly pin?: { readonly verts: readonly number[]; readonly keys: ReadonlyArray<readonly [number, number, number, number]>; readonly release?: readonly number[] };
  /** Debris only: the frame it lets go, its push (m/s) and spin (radians/s, about x, y, z) then. */
  readonly release?: { readonly frame: number; readonly velocity: Vec3; readonly spin: Vec3 };
}

export interface BlenderExchange {
  readonly version: number;
  readonly kind: BlenderEffectKind;
  readonly params: Readonly<Record<string, number | string | boolean>>;
  readonly fps: number;
  readonly frames: number;
  readonly render: { readonly width: number; readonly height: number };
  /** Show camera (Before Effects coordinates); its picture fills the canvas exactly. */
  readonly camera: { readonly eye: Vec3; readonly target: Vec3; readonly fovYDegrees: number };
  readonly photo?: string;
  readonly objects: readonly ExchangeObject[];
  /** Simulation box for smoke, fire and liquid (min and max corners). */
  readonly domain?: { readonly min: Vec3; readonly max: Vec3; readonly resolution: number };
  readonly output: { readonly blend: string; readonly frames: string; readonly cache: string };
}

/** A traced outline (canvas pixels, with holes) made into a solid `depth` metres deep, front at `front`. */
export const outlineSolid = (outline: readonly Vec2[], holes: ReadonlyArray<readonly Vec2[]>, canvas: Canvas, depth: number, front = 0): ExchangeMesh => {
  // Holes that touch the outline become notches (see solidWithHoles): clip first.
  const ring = (pts: readonly Vec2[]): [number, number][] => pts.map((p) => [p[0], p[1]]);
  let polys: Array<{ outer: Vec2[]; holes: Vec2[][] }>;
  try {
    const open = (r: [number, number][]): Vec2[] => (r.length > 1 && r[0]![0] === r.at(-1)![0] && r[0]![1] === r.at(-1)![1] ? r.slice(0, -1) : r) as Vec2[];
    polys = polygonClipping.difference([ring(outline)], ...holes.filter((h) => h.length >= 3).map((h) => [ring(h)])).map((p) => ({ outer: open(p[0]!), holes: p.slice(1).map(open) }));
  } catch {
    polys = [{ outer: [...outline], holes: [] }];
  }
  const verts: Array<[number, number, number]> = [];
  const uvs: Array<[number, number]> = [];
  const tris: Array<[number, number, number]> = [];
  for (const poly of polys) {
    const rings = [poly.outer, ...poly.holes];
    const flat: number[] = [];
    const starts: number[] = [];
    for (const [k, r] of rings.entries()) {
      if (k) starts.push(flat.length / 2);
      for (const p of r) flat.push(p[0], p[1]);
    }
    const n = flat.length / 2;
    const base = verts.length;
    // Front vertices then back vertices.
    for (let i = 0; i < n; i++) {
      const w = canvasToWorld([flat[i * 2]!, flat[i * 2 + 1]!], canvas);
      verts.push([w[0], w[1], front]);
      uvs.push([flat[i * 2]! / canvas.width, flat[i * 2 + 1]! / canvas.height]);
    }
    for (let i = 0; i < n; i++) {
      const w = canvasToWorld([flat[i * 2]!, flat[i * 2 + 1]!], canvas);
      verts.push([w[0], w[1], front - depth]);
      uvs.push([flat[i * 2]! / canvas.width, flat[i * 2 + 1]! / canvas.height]);
    }
    const idx = earcut(flat, starts);
    for (let i = 0; i < idx.length; i += 3) {
      // Canvas y runs down, world y up: earcut's order flips; front faces the audience (+z).
      tris.push([base + idx[i]!, base + idx[i + 2]!, base + idx[i + 1]!]);
      tris.push([base + n + idx[i]!, base + n + idx[i + 1]!, base + n + idx[i + 2]!]);
    }
    // Sides of every ring.
    let start = 0;
    for (const r of rings) {
      for (let i = 0; i < r.length; i++) {
        const a = base + start + i, b = base + start + ((i + 1) % r.length);
        tris.push([a, b, b + n], [a, b + n, a + n]);
      }
      start += r.length;
    }
  }
  return { verts, tris, uvs };
};

const closedPoints = (path: Parameters<typeof flattenPath>[0]): Vec2[] => {
  const pts = flattenPath(path, 8);
  if (pts.length > 2 && Math.hypot(pts[0]![0] - pts.at(-1)![0], pts[0]![1] - pts.at(-1)![1]) < 1e-6) pts.pop();
  return pts;
};

/** Bounds of areas in metres. */
const worldBounds = (pts: readonly Vec2[], canvas: Canvas) => {
  const w = pts.map((p) => canvasToWorld(p, canvas));
  const xs = w.map((p) => p[0]), ys = w.map((p) => p[1]);
  return { x0: Math.min(...xs), x1: Math.max(...xs), y0: Math.min(...ys), y1: Math.max(...ys) };
};

/** A piece in its own space (centred, front at +depth/2), scaled: what Before Effects draws for it. */
const pieceSolid = (piece: ResolvedPiece, sc: Vec3): ExchangeMesh => {
  const d = piece.depth / 2;
  const rings = [piece.outline, ...piece.holes].map((r) => r.map((p) => [p[0] * sc[0], p[1] * sc[1]] as const));
  const flat: number[] = [];
  const starts: number[] = [];
  for (const [k, r] of rings.entries()) {
    if (k) starts.push(flat.length / 2);
    for (const p of r) flat.push(p[0], p[1]);
  }
  const n = flat.length / 2;
  const verts: Array<[number, number, number]> = [];
  for (let i = 0; i < n; i++) verts.push([flat[i * 2]!, flat[i * 2 + 1]!, d * sc[2]]);
  for (let i = 0; i < n; i++) verts.push([flat[i * 2]!, flat[i * 2 + 1]!, -d * sc[2]]);
  const tris: Array<[number, number, number]> = [];
  const idx = earcut(flat, starts);
  for (let i = 0; i < idx.length; i += 3) {
    tris.push([idx[i]!, idx[i + 1]!, idx[i + 2]!]);
    tris.push([n + idx[i]!, n + idx[i + 2]!, n + idx[i + 1]!]);
  }
  let start = 0;
  for (const r of rings) {
    for (let i = 0; i < r.length; i++) {
      const a = start + i, b = start + ((i + 1) % r.length);
      tris.push([a, b, n + b], [a, n + b, n + a]);
    }
    start += r.length;
  }
  return { verts, tris };
};

const boxSolid = (h: Vec3): ExchangeMesh => {
  const verts: Array<[number, number, number]> = [];
  for (const z of [h[2], -h[2]]) for (const [x, y] of [[-h[0], -h[1]], [h[0], -h[1]], [h[0], h[1]], [-h[0], h[1]]] as const) verts.push([x, y, z]);
  const tris: Array<[number, number, number]> = [[0, 1, 2], [0, 2, 3], [4, 6, 5], [4, 7, 6], [0, 4, 5], [0, 5, 1], [1, 5, 6], [1, 6, 2], [2, 6, 7], [2, 7, 3], [3, 7, 4], [3, 4, 0]];
  return { verts, tris };
};

/**
 * Motion Before Effects already prepared with its own physics (Rapier) — the moving bodies of a 3D
 * scene layer in the show — as obstacles Blender plays back frame by frame and never simulates
 * (owner before-effects): smoke and water flow around falling pieces, cloth lands on them. The
 * scene's fixed solids (the ledge or plinth the pieces land on) come along as still obstacles. Also
 * returns the areas the pieces stand in for, whose still copies the exchange then leaves out.
 * `motion` is the prepared poses (7 floats per moving body per frame, from the layer's start).
 */
export const preparedObstacles = (
  project: Project,
  venueId: Id,
  r: ResolvedScene3D,
  motion: Float32Array,
  o: { layerName: string; layerStartSeconds: number; startSeconds: number; frames: number; fps: number },
): { objects: ExchangeObject[]; regionIds: Id[] } => {
  const ph = r.physics;
  if (!ph) return { objects: [], regionIds: [] };
  const objects: ExchangeObject[] = [];
  const regionIds = new Set<Id>();
  // Blender frame k (from 1) shows show time startSeconds + (k−1)/fps: the prepared frame at that moment.
  const poses = (index: number) =>
    Array.from({ length: o.frames }, (_, k) => {
      const f = Math.min(ph.frames - 1, Math.max(0, Math.round((o.startSeconds + k / o.fps - o.layerStartSeconds) * ph.fps)));
      const off = (f * ph.movers + index) * 7;
      return Array.from(motion.subarray(off, off + 7));
    });
  for (const ro of r.objects) {
    const ob = ro.object;
    const g = ob.geometry;
    if (!g) continue;
    if (ro.poseIndex < 0) {
      // A fixed box (ledge, plinth, ground) where it stands: what the pieces land on.
      if (ob.kind !== "mesh" || ob.physics?.body !== "static" || g.kind !== "box") continue;
      const pos = evalProp(ob.position, 0), q = eulerDegToQuat(evalProp(ob.rotation, 0)), sc = evalProp(ob.scale, 0).map((v) => v / 100) as unknown as Vec3;
      const box = boxSolid([g.size[0] / 2, g.size[1] / 2, g.size[2] / 2]);
      objects.push({ name: `${o.layerName}: ${ob.name}`, owner: "before-effects", role: "obstacle", mesh: { verts: box.verts.map((c) => placePoint(c as Vec3, pos, q, sc, ob.pivot)), tris: box.tris } });
      continue;
    }
    const t0 = secondsToTime(ob.fracture?.collapseAt ?? 0);
    const sc = evalProp(ob.scale, t0).map((v) => v / 100) as unknown as Vec3;
    if (g.kind === "area") {
      for (const reg of refRegions(project, g.ref, venueId)) regionIds.add(reg.id);
      ro.pieces.forEach((piece, i) => objects.push({ name: `${o.layerName}: ${ob.name} ${i + 1}`, owner: "before-effects", role: "obstacle", mesh: pieceSolid(piece, sc), motion: poses(ro.poseIndex + i) }));
    } else {
      const half: Vec3 =
        g.kind === "box" ? [(g.size[0] * sc[0]) / 2, (g.size[1] * sc[1]) / 2, (g.size[2] * sc[2]) / 2]
        : g.kind === "plane" ? [(g.size[0] * sc[0]) / 2, (g.size[1] * sc[1]) / 2, 0.01]
        : [g.radius * sc[0], g.radius * sc[1], g.radius * sc[2]];
      objects.push({ name: `${o.layerName}: ${ob.name}`, owner: "before-effects", role: "obstacle", mesh: boxSolid(half), motion: poses(ro.poseIndex) });
    }
  }
  return { objects, regionIds: [...regionIds] };
};

/**
 * The cloth for "Cloth reveal": a sheet hanging just in front of the areas (a little larger than
 * them), held along its top edge. At `revealAt` (0..1 of the length) the edge gives a small tug
 * toward the audience and lets go, left to right, and the sheet falls and crumples on the ground.
 */
export const clothSheet = (b: { x0: number; x1: number; y0: number; y1: number }, frames: number, revealAt = 0.3): ExchangeObject => {
  const w = b.x1 - b.x0, h = b.y1 - b.y0;
  const pad = Math.max(0.15, Math.min(w, h) * 0.06);
  const x0 = b.x0 - pad, y1 = b.y1 + pad, sw = w + 2 * pad, sh = h + 2 * pad;
  // About 10 cm squares, at least 16 and at most 64 a side.
  const nx = Math.max(16, Math.min(64, Math.round(sw / 0.1))), ny = Math.max(16, Math.min(64, Math.round(sh / 0.1)));
  const verts: Array<[number, number, number]> = [], tris: Array<[number, number, number]> = [], uvs: Array<[number, number]> = [];
  for (let j = 0; j <= ny; j++)
    for (let i = 0; i <= nx; i++) {
      verts.push([x0 + (sw * i) / nx, y1 - (sh * j) / ny, 0.15]);
      uvs.push([i / nx, j / ny]);
    }
  for (let j = 0; j < ny; j++)
    for (let i = 0; i < nx; i++) {
      const a = j * (nx + 1) + i;
      // Facing the audience (+z).
      tris.push([a, a + nx + 1, a + 1], [a + 1, a + nx + 1, a + nx + 2]);
    }
  const start = Math.max(10, Math.round(frames * Math.min(0.9, Math.max(0, revealAt))));
  const keys: Array<[number, number, number, number]> = [
    [1, 0, 0, 0],
    [start - 8, 0, 0, 0],
    [start, 0, 0.1, 0.4],
  ];
  const held = Array.from({ length: nx + 1 }, (_, i) => i);
  // Lets go over a quarter of a second, left to right.
  const release = held.map((i) => start + Math.round((8 * i) / nx));
  return { name: "Cloth", owner: "blender", role: "cloth", mesh: { verts, tris, uvs }, pin: { verts: held, keys, release } };
};

/**
 * "Break apart": the areas cut into Voronoi pieces (the same fracture as the built-in collapse),
 * each a photo-faced slab owned by Blender with the frame it lets go, its push toward the audience
 * and its spin; plus a dark backdrop where they were (what the hole shows).
 */
export const shatterPieces = (
  areas: ReadonlyArray<{ name: string; outline: readonly Vec2[]; holes: ReadonlyArray<readonly Vec2[]> }>,
  canvas: Canvas,
  fps: number,
  frames: number,
  params: Readonly<Record<string, number | string | boolean>>,
): ExchangeObject[] => {
  const num = (k: string, d: number) => (typeof params[k] === "number" && Number.isFinite(params[k]) ? (params[k] as number) : d);
  const size = Math.max(15, num("pieceSize", 60));
  const seed = Math.round(num("seed", 1));
  const push = num("push", 1.5), spin = num("spin", 0.5) * 2 * Math.PI, stagger = Math.max(0, num("stagger", 0));
  const breakFrame = Math.min(frames - 1, Math.max(1, Math.round(num("breakAt", 1) * fps) + 1));
  const depth = 0.12;
  const out: ExchangeObject[] = [];
  for (const a of areas) {
    const cells = fracture(a.outline, a.holes, size, seed).slice(0, 400);
    const ys = cells.map((c) => c.reduce((s, q) => s + q[1], 0) / c.length);
    const top = Math.min(...ys), span = Math.max(1e-6, Math.max(...ys) - top);
    cells.forEach((cell, i) => {
      const r = (k: number) => rand01(seed, i, k);
      // Height 1 at the top (canvas y runs down).
      const h = 1 - (ys[i]! - top) / span;
      const frame = Math.min(frames, breakFrame + Math.round(stagger * fps * Math.min(1, (1 - h) * (0.85 + 0.3 * r(1)))));
      out.push({
        name: `Piece: ${a.name} ${i + 1}`,
        owner: "blender",
        role: "debris",
        photo: true,
        mesh: outlineSolid(cell, [], canvas, depth, 0),
        release: {
          frame,
          velocity: [(r(2) - 0.5) * push * 0.5, (r(3) - 0.3) * push * 0.3, push * (0.2 + 1.6 * h) * (0.7 + 0.6 * r(4))],
          spin: [(r(3) - 0.5) * spin, (r(4) - 0.5) * spin, (r(2) - 0.5) * spin],
        },
      });
    });
    out.push({ name: `Behind: ${a.name}`, owner: "before-effects", role: "backdrop", mesh: outlineSolid(a.outline, a.holes, canvas, 0.02, -depth - 0.01) });
  }
  return out;
};

/**
 * Build the exchange for an effect link: the building (the facade with its openings, every other
 * traced area that's solid) as holdout obstacles owned by Before Effects, the effect's emitter (or
 * cloth) owned by Blender, the show camera and the simulation box.
 */
export const buildExchange = (
  project: Project,
  link: BlenderLink,
  o: {
    venueId: Id;
    canvas: Canvas;
    fps: number;
    photo?: string;
    output: BlenderExchange["output"];
    cameraDistance?: number;
    resolution?: number;
    /** Moving bodies Before Effects prepared (see preparedObstacles), and the areas they replace. */
    prepared?: { objects: readonly ExchangeObject[]; regionIds: readonly Id[] };
  },
): BlenderExchange => {
  const effect = link.effect;
  if (!effect) throw new Error("Only effect links have an exchange; linked files are rendered as they are.");
  const venue = project.venues[o.venueId];
  if (!venue) throw new Error("No venue.");
  const canvas = o.canvas;
  const objects: ExchangeObject[] = [];
  // The building: the facade (wall areas) and the other solid areas, owned by Before Effects.
  const solids = Object.values(venue.regions).filter((r) => r.path.closed && !r.proposal && r.kind !== "exclusion");
  const isEmitter = new Set(effect.regionIds);
  const replaced = new Set(o.prepared?.regionIds ?? []);
  for (const r of solids) {
    if (isEmitter.has(r.id) && effect.kind !== "cloth") continue;
    // Shown by moving pieces instead (prepared physics), added below.
    if (replaced.has(r.id)) continue;
    const depth = r.kind === "wall" ? 0.25 : 0.08;
    objects.push({ name: `Area: ${r.name}`, owner: "before-effects", role: "obstacle", mesh: outlineSolid(closedPoints(r.path), regionHoles(r, venue).map(closedPoints), canvas, depth, r.kind === "wall" ? 0 : -0.005) });
  }
  objects.push(...(o.prepared?.objects ?? []));
  // The ground at the foot of the house (an obstacle for liquid and cloth; not drawn).
  const all = solids.flatMap((r) => closedPoints(r.path));
  const house = all.length ? worldBounds(all, canvas) : { x0: -canvas.width * METERS_PER_PIXEL / 2, x1: canvas.width * METERS_PER_PIXEL / 2, y0: 0, y1: canvas.height * METERS_PER_PIXEL };
  const W = canvas.width * METERS_PER_PIXEL, H = canvas.height * METERS_PER_PIXEL;
  objects.push({
    name: "Ground",
    owner: "before-effects",
    role: "ground",
    mesh: { verts: [[-W, house.y0, 6], [W, house.y0, 6], [W, house.y0, -6], [-W, house.y0, -6], [-W, house.y0 - 0.2, 6], [W, house.y0 - 0.2, 6], [W, house.y0 - 0.2, -6], [-W, house.y0 - 0.2, -6]], tris: [[0, 1, 2], [0, 2, 3], [4, 6, 5], [4, 7, 6]] },
  });
  // The effect itself, owned by Blender.
  const areas = refRegions(project, { role: "areas", regionIds: [...effect.regionIds] }, o.venueId).filter((r) => r.path.closed);
  if (!areas.length) throw new Error("The effect's areas no longer exist.");
  const src = areas.flatMap((r) => closedPoints(r.path));
  const b = worldBounds(src, canvas);
  const frames0 = Math.max(1, Math.round(link.seconds * o.fps));
  if (effect.kind === "shatter") objects.push(...shatterPieces(areas.map((r) => ({ name: r.name, outline: closedPoints(r.path), holes: regionHoles(r, venue).map(closedPoints) })), canvas, o.fps, frames0, effect.params));
  for (const r of areas) {
    if (effect.kind === "cloth" || effect.kind === "shatter") continue;
    // A thin slab just in front of the area: where smoke, fire or water comes from.
    objects.push({ name: `Emitter: ${r.name}`, owner: "blender", role: "emitter", mesh: outlineSolid(closedPoints(r.path), [], canvas, 0.06, 0.08) });
  }
  const frames = Math.max(1, Math.round(link.seconds * o.fps));
  // "Lets go at" is in seconds from the effect's start.
  if (effect.kind === "cloth") objects.push(clothSheet(b, frames, Math.min(0.9, (Number(effect.params.revealAt ?? 1.2) * o.fps) / frames)));
  const cam = showCamera(canvas, o.cameraDistance ?? 1.6);
  const w = b.x1 - b.x0, h = b.y1 - b.y0;
  const domain =
    effect.kind === "smoke" || effect.kind === "fire"
      ? // Room to spread sideways and rise; no bigger than needed, since the cells scale with it.
        { min: [Math.max(-W / 2, b.x0 - Math.max(1, w * 0.5)), Math.max(house.y0, b.y0 - 0.3), -0.6] as Vec3, max: [Math.min(W / 2, b.x1 + Math.max(1, w * 0.5)), Math.min(H + 1, Math.max(b.y1 + Math.max(3, h), house.y1 + 1)), 3] as Vec3 }
      : effect.kind === "liquid"
        ? { min: [Math.max(-W / 2, b.x0 - w * 1.5 - 1), house.y0 - 0.1, -0.6] as Vec3, max: [Math.min(W / 2, b.x1 + w * 1.5 + 1), b.y1 + 0.5, 4] as Vec3 }
        : undefined;
  const width = link.quality === "full" ? canvas.width : Math.round(canvas.width / 2);
  const height = link.quality === "full" ? canvas.height : Math.round(canvas.height / 2);
  return {
    version: EXCHANGE_VERSION,
    kind: effect.kind,
    params: effect.params,
    fps: o.fps,
    frames,
    render: { width, height },
    camera: { eye: cam.eye, target: cam.target, fovYDegrees: cam.fovY },
    ...(o.photo ? { photo: o.photo } : {}),
    objects,
    ...(domain ? { domain: { ...domain, resolution: o.resolution ?? (link.quality === "full" ? 160 : 96) } } : {}),
    output: o.output,
  };
};

/** One owner per object: refuse an exchange where Before Effects and Blender would both move something. */
export const checkOwners = (x: BlenderExchange): string[] => {
  const problems: string[] = [];
  const seen = new Map<string, string>();
  for (const ob of x.objects) {
    const prev = seen.get(ob.name);
    if (prev && prev !== ob.owner) problems.push(`"${ob.name}" would be moved by both Before Effects and Blender.`);
    seen.set(ob.name, ob.owner);
    if (ob.owner === "blender" && ob.motion) problems.push(`"${ob.name}" is simulated by Blender but also has motion from Before Effects.`);
    if (ob.owner === "before-effects" && (ob.role === "emitter" || ob.role === "cloth" || ob.role === "debris")) problems.push(`"${ob.name}" is a ${ob.role} but isn't owned by Blender.`);
  }
  return problems;
};
