/** pnpm register:report — regenerate docs/register/REPORT.md from the register files. */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { ACTIVE_DISPOSITIONS, DISPOSITIONS, type Entry, loadRegister, MILESTONES, REGISTER_DIR, STATUSES } from "./load.ts";

const { entries, errors, warnings } = loadRegister();
const by = <K extends string>(xs: Entry[], f: (e: Entry) => K) => xs.reduce((m, e) => m.set(f(e), [...(m.get(f(e)) ?? []), e]), new Map<K, Entry[]>());
const domain = (e: Entry) => (e.id.startsWith("fx.") ? `fx.${e.id.split(".")[1]}` : e.id.split(".")[0]!);

const isDeferred = (e: Entry) => e.disposition === "deferred";
const deferred = entries.filter(isDeferred);
const active = entries.filter((e) => ACTIVE_DISPOSITIONS.includes(e.disposition));

const lines: string[] = [];
lines.push("# Capability register — report", "");
lines.push(`Generated by \`pnpm register:report\` on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.`, "");
lines.push(`**${entries.length} entries** in ${new Set(entries.map((e) => e.file)).size} files (${active.length} active, ${deferred.length} deferred) · ${errors.length} validation errors · ${warnings.length} warnings.`, "");
lines.push("Scope: projection workflows (brief 2026-10-02, projection scope). Deferred entries are valid capabilities that After Effects parity would need but projection shows do not need now. See `SCHEMA.md`, \"Projection scope\".", "");

lines.push("## Status by milestone (excluding deferred entries)", "", `| Milestone | ${STATUSES.join(" | ")} | total | deferred (not counted) |`, `|---|${STATUSES.map(() => "---:").join("|")}|---:|---:|`);
const byM = by(entries, (e) => e.milestone);
for (const m of MILESTONES) {
  const all = byM.get(m) ?? [];
  const xs = all.filter((e) => !isDeferred(e));
  lines.push(`| ${m} | ${STATUSES.map((s) => xs.filter((e) => e.status === s).length).join(" | ")} | ${xs.length} | ${all.length - xs.length} |`);
}
lines.push("", "## Dispositions", "", "| Disposition | Count |", "|---|---:|");
for (const d of DISPOSITIONS) lines.push(`| ${d} | ${entries.filter((e) => e.disposition === d).length} |`);

lines.push("", "## Areas", "", "| Area | Entries | Deferred | Milestone B (active) | Not checked against live source |", "|---|---:|---:|---:|---:|");
for (const [d, xs] of [...by(entries, domain)].sort()) {
  lines.push(`| ${d} | ${xs.length} | ${xs.filter(isDeferred).length} | ${xs.filter((e) => e.milestone === "B" && !isDeferred(e)).length} | ${xs.filter((e) => e.sources.some((s) => !s.checked)).length} |`);
}

lines.push("", "## Deferred (revisit later)", "", `${deferred.length} entries are deferred: valid capabilities that are not needed for projection workflows now. Each carries a \`deferred_reason\`. Their \`status\` and \`evidence\` are unchanged.`, "");
const deferredWithWork = deferred.filter((e) => e.status !== "not-started");
lines.push("### Deferred entries that already have work", "");
if (deferredWithWork.length === 0) lines.push("None.");
for (const e of deferredWithWork.sort((a, b) => a.id.localeCompare(b.id))) lines.push(`- \`${e.id}\` ${e.name} — *${e.status}*`);
const supersededByDeferred = entries.filter((e) => e.disposition === "superseded" && e.superseded_by && deferred.some((d) => d.id === e.superseded_by));
lines.push("", "### Superseded entries whose replacement is deferred", "");
if (supersededByDeferred.length === 0) lines.push("None.");
for (const e of supersededByDeferred.sort((a, b) => a.id.localeCompare(b.id))) lines.push(`- \`${e.id}\` → \`${e.superseded_by}\``);
lines.push("", `<details><summary>All deferred entries (${deferred.length})</summary>`, "");
for (const [d, xs] of [...by(deferred, domain)].sort()) {
  lines.push(`**${d}** (${xs.length})`, "");
  for (const e of xs.sort((a, b) => a.id.localeCompare(b.id))) lines.push(`- \`${e.id}\` ${e.name}`);
  lines.push("");
}
lines.push("</details>");

const unresolved = entries.filter((e) => e.disposition === "unresolved");
lines.push("", "## Open questions (unresolved relevance)", "");
if (unresolved.length === 0) lines.push("None.");
for (const e of unresolved) lines.push(`- **${e.id}** — ${e.name}: ${(e.limitations ?? "").replace(/\s+/g, " ").trim()}`);

lines.push("", "## Milestone B scope (active entries)", "");
for (const e of entries.filter((x) => x.milestone === "B" && !isDeferred(x)).sort((a, b) => a.id.localeCompare(b.id))) lines.push(`- \`${e.id}\` ${e.name} — *${e.status}*`);

if (warnings.length) {
  lines.push("", "## Warnings", "");
  for (const w of warnings) lines.push(`- ${w}`);
}
writeFileSync(join(REGISTER_DIR, "REPORT.md"), `${lines.join("\n")}\n`);
console.log(`Wrote REPORT.md (${entries.length} entries)`);
