"""Generate packages/aep/src/tables.generated.ts from py_aep's data tables.

Exports plain data only (display names for match names, and the default
children After Effects reports for groups whose untouched children it does
not store in the .aep). Run with a Python that has py_aep importable:

    python packages/aep/scripts/gen-tables.py > packages/aep/src/tables.generated.ts

Data from py_aep (MIT, (c) 2023 Fortiche production, https://github.com/forticheprod/py-aep).
"""

from __future__ import annotations

import json
import math

from py_aep.data.match_names import MATCH_NAME_TO_AUTO_NAME
from py_aep.models.properties.overrides import _NAME_OVERRIDES
from py_aep.synthesis import property as synth

# Groups whose defaults we do not synthesize: Layer Styles are not imported,
# and the text-animator property pool lists every *possible* animator
# property rather than the ones a user added.
SKIP_GROUPS = {
    "ADBE Layer Styles",
    "ADBE Blend Options Group",
    "ADBE Adv Blend Group",
    "ADBE Text Animator Properties",
}


def num(v):
    if isinstance(v, bool):
        return int(v)
    if isinstance(v, float):
        if math.isinf(v) or math.isnan(v):
            return None
        if v.is_integer():
            return int(v)
        return float(repr(v))
    return v


def value(v):
    if v is None:
        return None
    if isinstance(v, (list, tuple)):
        return [num(x) for x in v]
    if isinstance(v, (int, float)):
        return num(v)
    return None


def spec_entry(s):
    if isinstance(s, synth.GroupSpec):
        e = {"m": s.match_name, "n": s.auto_name, "g": 1}
        if s.min_major:
            e["mm"] = s.min_major
        return e
    e = {"m": s.match_name, "n": s.auto_name, "t": int(s.pvt)}
    v = value(s.value)
    if v is not None:
        e["v"] = v
    if s.color:
        e["c"] = 1
    if s.min_major:
        e["mm"] = s.min_major
    return e


def main():
    out = []
    out.append("// GENERATED by packages/aep/scripts/gen-tables.py - do not edit by hand.")
    out.append("// Data from py_aep (MIT, (c) 2023 Fortiche production, https://github.com/forticheprod/py-aep).")
    out.append("/* eslint-disable */")
    out.append("")
    out.append("/** Display name After Effects shows for a property when the file stores no name of its own. */")
    names = dict(MATCH_NAME_TO_AUTO_NAME)
    # Names from the synthesis specs fill in groups the main table lacks.
    all_specs = list(synth._TOP_LEVEL_SPECS) + list(synth._PARAMETRIC_MESH_TOP_LEVEL_SPECS) + list(synth._TRANSFORM_SPECS)
    for specs in synth._GROUP_CHILD_SPECS.values():
        all_specs.extend(specs)
    for s in all_specs:
        names.setdefault(s.match_name, s.auto_name)
    out.append("export const MATCH_NAME_DISPLAY: Readonly<Record<string, string>> = " + json.dumps(names, ensure_ascii=False, indent=0, sort_keys=True) + ";")
    out.append("")
    out.append("/** Names AE reports regardless of what the file stores (mostly hidden effect controls). */")
    out.append("export const NAME_OVERRIDES: Readonly<Record<string, string>> = " + json.dumps(dict(_NAME_OVERRIDES), ensure_ascii=False, indent=0, sort_keys=True) + ";")
    out.append("")
    out.append("/** A child After Effects always reports in a group: m = match name, n = display name, g = group,")
    out.append(" *  t = PropertyValueType, v = default value (ExtendScript units), c = colour, mm = first AE major version. */")
    out.append("export interface ChildSpec { readonly m: string; readonly n: string; readonly g?: 1; readonly t?: number; readonly v?: number | readonly number[]; readonly c?: 1; readonly mm?: number }")
    out.append("")
    groups = {}
    for mn, specs in synth._GROUP_CHILD_SPECS.items():
        if mn in SKIP_GROUPS:
            continue
        groups[mn] = [spec_entry(s) for s in specs]
    out.append("export const GROUP_CHILDREN: Readonly<Record<string, readonly ChildSpec[]>> = {")
    for mn in sorted(groups):
        out.append("  " + json.dumps(mn) + ": [")
        for e in groups[mn]:
            out.append("    " + json.dumps(e, ensure_ascii=False) + ",")
        out.append("  ],")
    out.append("};")
    out.append("")
    out.append("/** The twelve Transform children ExtendScript always reports, in order. */")
    out.append("export const TRANSFORM_CHILDREN: readonly ChildSpec[] = [")
    for s in synth._TRANSFORM_SPECS:
        e = spec_entry(s)
        d = synth._TRANSFORM_FIXED_DEFAULTS.get(s.match_name)
        if d is not None:
            e["v"] = value(d)
        out.append("  " + json.dumps(e) + ",")
    out.append("];")
    out.append("")
    out.append("/** A layer's top-level groups in ExtendScript order (regular layers, then parametric mesh layers). */")
    out.append("export const TOP_LEVEL: readonly ChildSpec[] = [")
    for s in synth._TOP_LEVEL_SPECS:
        out.append("  " + json.dumps(spec_entry(s)) + ",")
    out.append("];")
    out.append("export const MESH_TOP_LEVEL: readonly ChildSpec[] = [")
    for s in synth._PARAMETRIC_MESH_TOP_LEVEL_SPECS:
        out.append("  " + json.dumps(spec_entry(s)) + ",")
    out.append("];")
    out.append("/** Top-level groups each kind of layer does not have. */")
    out.append("export const TOP_LEVEL_SKIP: Readonly<Record<string, readonly string[]>> = " + json.dumps({
        "av": sorted(synth._SKIP_FOR_REGULAR_AV),
        "text": sorted(synth._SKIP_FOR_TEXT),
        "shape": sorted(synth._SKIP_FOR_SHAPE),
        "camera": sorted(synth._SKIP_FOR_CAMERA),
        "light": sorted(synth._SKIP_FOR_LIGHT),
    }, indent=1) + ";")
    out.append("")
    print("\n".join(out))


if __name__ == "__main__":
    main()
